# 評価時に使用する報酬
# すべて1に設定し、達成回数をカウントする
original_reward:
  finish_payment: 1.0 # 会計を完了し、客が退店したら報酬
shaped_reward: # 細かいステップごとに得られる報酬
  invite_customer: 1.0 # 客を案内
  refuse_customer: 1.0 # 満席時、客を帰す
  take_order: 1.0 # 注文を取る
  wash_plate: 1.0 # 皿を洗う
  process_payment: 1.0 # 会計処理をする(未完)
  clean_dirt: 1.0 # 汚れを掃除する
  ## pick
  pickup_ingredient_from_pile: 1.0 # 食材をpileから取り出す
  pickup_ingredient_from_counter: 1.0 # 食材をカウンターから取り上げる
  pickup_new_plate_from_pile: 1.0 # 皿をpileから取り出す
  pickup_new_plate_from_counter: 1.0 # 皿をカウンターから取り上げる
  plate_dish: 1.0 # 皿に料理を盛り付ける
  pickup_dish_from_counter: 1.0 # 料理をカウンターから取り上げる
  pickup_used_plate_from_table: 1.0 # 使用済み皿をテーブルから下げる
  clean_table: 1.0 # テーブルを片付ける(客が退店済み)
  pickup_used_plate_from_counter: 1.0 # 使用済み皿をカウンターから取り上げる
  ## place
  ### place ingredient
  placement_in_pot: 1.0 # 鍋に食材を入れる
  pot_start_cooking: 1.0 # 注文されたメニューの調理を開始する
  place_ingredient_on_counter: 1.0 # 食材をカウンターに置く
  dispose_ingredient: 1.0 # 食材をゴミ箱に捨てる
  ### place food
  deliver_food: 1.0 # 料理を提供する
  place_food_on_counter: 1.0 # 料理をカウンターに置く
  dispose_food: 1.0 # 料理をゴミ箱に捨てる
  ### place plate
  place_new_plate_on_counter: 1.0 # 新しい皿をカウンターに置く
  place_used_plate_on_counter: 1.0 # 使用済み皿をカウンターに置く
  soak_plate: 1.0 # 使用済み皿をシンクに置く
  pickup_plate: 1.0 # 皿を持つ
  pickup_ingredient: 1.0 # 食材を持つ
  dish_pickup: 1.0 # 皿に料理を盛り付ける
  retrieve_plate: 1.0 # 皿を下げる
penalty: # 抑止したい行動をとったときのペナルティ、Overcookedの処理でマイナス符号にする
  ineffective_interaction: 0.0 # 無効なinteractionを行った
  ineffective_pickup: 0.0 # 無効なinteractionを行った
  ineffective_placement: 0.0 # 無効なinteractionを行った
  erroneous_cooking: 0.0 # 注文されていない料理を調理した(事前に調理しておく場合もペナルティになる)
  erroneous_delivery: 0.0 # 注文と違う料理を提供しようとした
  step_cost: 0.0 # 移動にかかるコスト(無駄な動きを抑制)
  block_cost: 0.0 # 位置・向きの変わらない移動をした(壁押し)
discount: # 時間経過による報酬割引の設定
  decline_deliver_reward: false # 時間経過により料理提供の報酬を割り引くか
  deliver_ramp_step: 10 # 料理提供時の報酬が割引なしで与えられる注文からのステップ数
  deliver_limit_step: 100 # 料理提供の報酬が下がりきるステップ数(>deliver_ramp_step)
  deliver_discount_rate: 0.0 # 報酬割引率の下限
