opening_time: 10 # 開店時間
closing_time: 720 # 閉店時間
terminal_time: 780 # 終了時間
reservation: # 予約客の来店時間(ステップ数で指定)
  - 1
  - 10
  - 30
# 一般客の来店率の時間変化
# [変更ステップ数, 来店率(%)]のリスト
# 例)
# - [0, 0]    0step目から次の指定があるstepまで来店率0%
# - [12, 10]  12step目から次の指定があるstepまで来店率10%
#   :         以下同様に続ける
congestion_rates:
  - [0, 0]
  - [10, 10]
  - [20, 100]
  - [25, 20]
  - [30, 50]
  - [35, 0]
  - [50, 20]
